BEGIN;

SELECT set_config('atlas.batch_id','atlas-first-slice-20261008',true);

INSERT INTO atlas.sources(id,title,locator,publisher,source_kind,published_date,accessed_date,scope,limitations,provenance) VALUES ('source-who-ageing-2025','Ageing and health','https://www.who.int/news-room/fact-sheets/detail/ageing-and-health','World Health Organization','institutional','2025-10-01','2026-10-08','Global overview of ageing, environments and public-health responses.','Broad institutional synthesis; no local field observation or prevalence estimate for this atlas slice.','{"read_method":"web page inspected","sections":["Factors influencing healthy ageing","WHO response"]}'::jsonb);

INSERT INTO atlas.sources(id,title,locator,publisher,source_kind,published_date,accessed_date,scope,limitations,provenance) VALUES ('source-amara-product-20261008','Amara Home product page','https://amara.app/','Amara','provider_claim',NULL,'2026-10-08','Provider description of a preconfigured voice-operated device and family app.','Self-description of an offering; no independent outcome or unmet-need evidence.','{"read_method":"web page inspected","existing_entry_id":"company-amara"}'::jsonb);

INSERT INTO atlas.sources(id,title,locator,publisher,source_kind,published_date,accessed_date,scope,limitations,provenance) VALUES ('source-user-product-direction','Defining the atlas and authorized realignment request','chatgpt-conversation://6ac6aa26-312c-83eb-b973-f82acbe0770d','Project owner','product_direction',NULL,'2026-10-08','Product and model decisions, not empirical claims.','Cannot support factual claims about stakeholder experiences.','{"conversation_id":"6ac6aa26-312c-83eb-b973-f82acbe0770d"}'::jsonb);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('stakeholder-older-adults','stakeholder','Older adults','Include this perspective in the shared graph; investigate diversity within it.','normative','{"basis":"not_applicable","rationale":"Stakeholder inclusion is product direction, not a research finding."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('stakeholder-family-caregivers','stakeholder','Family caregivers','Include this perspective in the shared graph; investigate diversity within it.','normative','{"basis":"not_applicable","rationale":"Stakeholder inclusion is product direction, not a research finding."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('stakeholder-professional-caregivers','stakeholder','Professional caregivers','Include this perspective in the shared graph; investigate diversity within it.','normative','{"basis":"not_applicable","rationale":"Stakeholder inclusion is product direction, not a research finding."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('stakeholder-care-providers','stakeholder','Care providers','Include this perspective in the shared graph; investigate diversity within it.','normative','{"basis":"not_applicable","rationale":"Stakeholder inclusion is product direction, not a research finding."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('stakeholder-sustainable-innovators','stakeholder','Financially sustainable innovators','Include this perspective in the shared graph; investigate diversity within it.','normative','{"basis":"not_applicable","rationale":"Stakeholder inclusion is product direction, not a research finding."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('space-everyday-participation','problem_space','Participation in everyday life','Explore frictions between what people value doing and what their environments let them do. Scope includes home, neighbourhood and social participation, with overlaps into care work and provision. Excludes a general catalogue of diseases or communication products. Boundaries remain revisable.','interpretation','{"basis":"not_applicable","rationale":"Editorial boundary informed by WHO context; not a validated universal taxonomy."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('aspiration-valued-activities','aspiration','Continue activities that matter to me','Candidate aspiration to investigate in the person’s own terms: continue relationships and activities they value, with agency over help.','hypothesis','{"basis":"not_assessed","rationale":"Requires field research; not an observed or verified claim."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('problem-environmental-barriers','problem','Environments can obstruct valued activities','Physical and social environments can constrain what older people are able to do.','documented','{"basis":"single_source","rationale":"Supported at a broad global level by WHO; local mechanisms and distribution remain unresearched."}'::jsonb,'{"geography":"global","setting":"homes, neighbourhoods and communities","population":"older people; heterogeneous needs"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('cause-environment-capacity-fit','systemic_cause','Fit between environments and capacity','WHO describes environments as affecting health through barriers and incentives and enabling valued activity despite capacity loss. This is a broad mechanism, not a measured local causal effect.','documented','{"basis":"single_source","rationale":"Institutional synthesis; no local causal estimate."}'::jsonb,'{"geography":"global","setting":"physical and social environments","population":"older people"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('problem-digital-family-contact','problem','Difficulty initiating digital family contact','Candidate question: in which situations do digital interfaces obstruct family contact for an older person, and whose goal does contact serve?','candidate','{"basis":"not_assessed","rationale":"Requires field research; not an observed or verified claim."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('situation-family-call','daily_situation','Initiating a family call at home','Illustrative research scenario: a person wants to call family at a time they choose. No person, interview, quotation or frequency is asserted.','illustrative','{"basis":"not_applicable","rationale":"A prompt for fieldwork, not an observed day-in-the-life."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('workaround-family-assistance','lived_workaround','Ask a relative to operate the interface','Hypothesized workaround to investigate: relying on a relative to set up or initiate contact. Do not display as observed lived experience until field evidence exists.','hypothesis','{"basis":"not_assessed","rationale":"Requires field research; not an observed or verified claim."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('response-who-decade','institutional_response','UN Decade of Healthy Ageing','WHO describes a collaborative programme that includes supportive communities, integrated care and access to long-term care.','documented','{"basis":"single_source","rationale":"Documents an institutional response, not proof of its outcomes."}'::jsonb,'{"geography":"global","setting":"public-health systems","population":"older people, families and communities"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('solution-amara-home','solution','Amara Home','The provider describes a preconfigured voice-operated device and family app for calls, photos and messages. This documents the offering, not effectiveness against loneliness.','documented','{"basis":"single_source","rationale":"Provider claim inspected; no independent outcome evaluation."}'::jsonb,'{"geography":"not assessed","setting":"home","population":"older users and families"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,'company-amara');

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('question-lived-needs','open_question','Whose aspiration is being served?','What do older adults want from contact, and how does that differ from family expectations? Recruit varied circumstances; preserve attributed observations.','open_question','{"basis":"not_assessed","rationale":"Requires field research; not an observed or verified claim."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('question-care-work','open_question','How does participation relate to care work?','What effects do support arrangements have on professional caregivers, provider workload and sustainable service provision? No effect direction is assumed.','open_question','{"basis":"not_assessed","rationale":"Requires field research; not an observed or verified claim."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.objects(id,kind,title,statement,epistemic_status,confidence,scope,provenance,entry_id) VALUES ('question-response-outcomes','open_question','What does the response change?','Does easier initiation change valued contact, autonomy or work for families? Seek independent outcomes, costs, non-use and alternatives.','open_question','{"basis":"not_assessed","rationale":"Requires field research; not an observed or verified claim."}'::jsonb,'{"geography":"not established","setting":"not established","population":"not established"}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,NULL);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-env-in-space','problem-environmental-barriers','space-everyday-participation','part_of','Editorially grouped by the valued-activity friction.','interpretation','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-digital-in-space','problem-digital-family-contact','space-everyday-participation','part_of','Candidate subproblem, not a verified need.','interpretation','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-env-affects-older','problem-environmental-barriers','stakeholder-older-adults','affects','WHO explains environmental barriers and supportive environments for older people.','documented','{"basis":"single_source","rationale":"WHO broad institutional synthesis."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-env-mechanism','cause-environment-capacity-fit','problem-environmental-barriers','contributes_to','Environmental barriers and incentives are part of the broad mechanism described by WHO.','documented','{"basis":"single_source","rationale":"Broad mechanism; no local causal estimate."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-aspiration','stakeholder-older-adults','aspiration-valued-activities','aspires_to','Candidate aspiration; requires people’s own accounts.','hypothesis','{"basis":"not_assessed","rationale":"Not an attributed aspiration."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-situation','problem-digital-family-contact','situation-family-call','arises_in','Illustrative setting for investigating a candidate problem.','illustrative','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-workaround','workaround-family-assistance','problem-digital-family-contact','works_around','Potential reliance on family is a research hypothesis.','hypothesis','{"basis":"not_assessed","rationale":"No observed workaround yet."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-who-response','response-who-decade','problem-environmental-barriers','responds_to','WHO’s described response includes supportive communities.','documented','{"basis":"single_source","rationale":"Institutional response documented; outcomes not established."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-amara-response','solution-amara-home','problem-digital-family-contact','responds_to','The described offering is a response relevant to the candidate contact problem; this match is editorial and establishes neither unmet need nor effectiveness.','interpretation','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-family-affects','problem-digital-family-contact','stakeholder-family-caregivers','affects','Investigate how support burdens and family goals interact.','hypothesis','{"basis":"not_assessed","rationale":"Not measured."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-question-lived-needs','space-everyday-participation','question-lived-needs','raises_question','Keep this unanswered question visible.','interpretation','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-question-care-work','space-everyday-participation','question-care-work','raises_question','Keep this unanswered question visible.','interpretation','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.relationships(id,from_id,to_id,relation,statement,epistemic_status,confidence,provenance) VALUES ('rel-question-response-outcomes','space-everyday-participation','question-response-outcomes','raises_question','Keep this unanswered question visible.','interpretation','{"basis":"not_applicable","rationale":"Editorial connection, not empirical or causal verification."}'::jsonb,'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-problem-environmental-barriers','problem-environmental-barriers',NULL,'source-who-ageing-2025','supports','Factors influencing healthy ageing',NULL,'Paraphrase of WHO sections on physical and social environments. No local prevalence asserted.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-cause-environment-capacity-fit','cause-environment-capacity-fit',NULL,'source-who-ageing-2025','supports','Factors influencing healthy ageing',NULL,'WHO describes direct influences, barriers, incentives and support despite capacity loss.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-response-who-decade','response-who-decade',NULL,'source-who-ageing-2025','supports','WHO response',NULL,'Programme description; not an evaluation.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-amara','solution-amara-home',NULL,'source-amara-product-20261008','supports','Amara in 3 Schritten; Amara Home für Oma, eine App für Euch',NULL,'Offering described by provider. No loneliness outcome inferred.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-rel-env-affects-older',NULL,'rel-env-affects-older','source-who-ageing-2025','supports','Factors influencing healthy ageing; WHO response',NULL,'Scoped support for the stated broad relationship.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-rel-env-mechanism',NULL,'rel-env-mechanism','source-who-ageing-2025','supports','Factors influencing healthy ageing; WHO response',NULL,'Scoped support for the stated broad relationship.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-rel-who-response',NULL,'rel-who-response','source-who-ageing-2025','supports','Factors influencing healthy ageing; WHO response',NULL,'Scoped support for the stated broad relationship.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-space-origin','space-everyday-participation',NULL,'source-who-ageing-2025','context','Factors influencing healthy ageing',NULL,'Context for an editorial grouping; does not validate its boundaries.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-amara-response-origin',NULL,'rel-amara-response','source-amara-product-20261008','context','Amara in 3 Schritten',NULL,'Context for editorial response linkage; not independent need or outcome evidence.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-origin-stakeholder-older-adults','stakeholder-older-adults',NULL,'source-user-product-direction','origin','ethical-north-star',NULL,'Stakeholder inclusion follows product direction.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-origin-stakeholder-family-caregivers','stakeholder-family-caregivers',NULL,'source-user-product-direction','origin','ethical-north-star',NULL,'Stakeholder inclusion follows product direction.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-origin-stakeholder-professional-caregivers','stakeholder-professional-caregivers',NULL,'source-user-product-direction','origin','ethical-north-star',NULL,'Stakeholder inclusion follows product direction.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-origin-stakeholder-care-providers','stakeholder-care-providers',NULL,'source-user-product-direction','origin','ethical-north-star',NULL,'Stakeholder inclusion follows product direction.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.evidence_links(id,object_id,relationship_id,source_id,stance,locator,excerpt,note,reviewed_at,provenance) VALUES ('ev-origin-stakeholder-sustainable-innovators','stakeholder-sustainable-innovators',NULL,'source-user-product-direction','origin','ethical-north-star',NULL,'Stakeholder inclusion follows product direction.','2026-10-08T14:00:00Z','{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb);

INSERT INTO atlas.legacy_records(id,entry_id,original_document,original_row,note) SELECT 'legacy-'||id,id,document,to_jsonb(e),'Historical analyst record; unreviewed. No killed/standing decision implies problem validity or opportunity quality. No theme-to-problem mapping inferred.' FROM public.entries e WHERE type='idea';

INSERT INTO atlas.import_batches(id,title,state,expected_counts,actual_counts,provenance,note) VALUES ('earlier-research-48-384-50','Earlier problem research','pending_artifact','{"domains":48,"candidate_problems":384,"sources":50}'::jsonb,'{"domains":0,"candidate_problems":0,"sources":0}'::jsonb,'{"reported_in":"6ac6aa26-312c-83eb-b973-f82acbe0770d","searched":["available repository branches listing","main and ux tree","available git history","local project files","all database tables"]}'::jsonb,'Original artifact not located. Counts are reported expectations, not verified inventory. Do not reconstruct or promote candidates.');

INSERT INTO atlas.import_batches(id,title,state,expected_counts,actual_counts,provenance,note) VALUES ('legacy-ideas-20261008','Legacy idea records','staged','{}'::jsonb,jsonb_build_object('records',(SELECT count(*) FROM atlas.legacy_records)),'{"batch":"atlas-first-slice-20261008","authored_by":"Codex","method":"Scoped editorial curation, independently of company themes"}'::jsonb,'Lossless copies staged for review; not imported as verified problem objects.');

INSERT INTO atlas.migrations(id,description,manifest) VALUES ('002_first_slice','Limited scoped content, response linkage, lossless legacy staging and missing-artifact register','{"objects":17,"relationships":13,"sources":3,"evidence_links":14,"legacy_query":"public.entries WHERE type=''idea''","existing_tables_modified":[]}'::jsonb);

COMMIT;
