-- Display mapping for separately audited meals-reviewed-20261009 research import.
-- Requires its reviewed publication artifact; cannot create unsupported research records.
BEGIN;
SELECT set_config('atlas.batch_id','meals-navigation-media-20261009',true);
UPDATE atlas.objects SET scope=scope || '{"navigation": {"role": "need", "title": "I want to keep enjoying my meals", "short_title": "Enjoying meals", "summary": "Keep choice and enjoyment as household routines change.", "image": "assets/illustrations/study/need-meals-v2.png", "order": 6, "lenses": ["adult"], "affected_lenses": ["adult", "family"]}}'::jsonb WHERE id='wc-object-dae6a42b17e3ab844ddca033';
UPDATE atlas.objects SET scope=scope || '{"navigation": {"role": "situation", "title": "Some meals no longer feel worth cooking for one or two", "short_title": "Cooking for fewer people", "summary": "A smaller household can mean fewer dishes feel worth the effort.", "image": "assets/illustrations/study/situation-cook-small-v2.png", "order": 0, "remaining_question": "Which dishes, preparation demands and preferences matter now, and for whom do existing options fall short?"}, "counterpreferences": "Some participants valued more freedom and creativity after cooking for fewer people. Small households are not inherently a problem."}'::jsonb WHERE id='wc-object-dde890986303728bfbae998d';
UPDATE atlas.objects SET scope=scope || '{"navigation": {"role": "solution", "title": "Malteser Menüservice", "short_title": "Malteser meals", "summary": "Hot or frozen prepared meals, with a rotating menu and several ways to order."}, "provider": "Malteser; local operating legal entity not verified", "website": "https://www.malteser.de/menueservice.html", "eligibility": {"status": "published_partial", "summary": "Provider describes people temporarily or permanently unable to shop and cook; check the local service for individual access and delivery."}, "cost": {"status": "unknown", "summary": "Local menu prices are shown through the provider availability check; no price verified for a particular address."}, "limitations": "Provider description only. Local coverage, capacity, price and individual preference fit are unverified. Prepared meals may reduce preparation effort; improved enjoyment is not established. HOFMANNs is named as a partner where Malteser does not deliver."}'::jsonb WHERE id='wc-object-b687a95988852b49c837c4c2';
UPDATE atlas.relationships SET provenance=provenance || '{"navigation":true}'::jsonb WHERE id='wc-relationship-1be01523cfb3aa455be3369c';
UPDATE atlas.relationships SET provenance=provenance || '{"navigation":true}'::jsonb WHERE id='wc-relationship-6fcc94267172fbc16d16381f';
COMMIT;
